version: '3.1'

services:
  node:
    build:
      context: .
      dockerfile: node.Dockerfile
    command: yarn start
    restart: always
    volumes:
      - './src:/var/www/project/src'
    ports:
      - '8081:8081'
    environment:
      NODE_ENV: development
      NODE_PORT: 8081
      DB_HOST: db
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASS: password
      REDIS_URL: redis
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - '8080:443'
    depends_on:
      - node
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs:ro
    environment:
      - DEFAULT_HOST=node:8081

  db:
    image: postgres:10
    restart: always
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - ./src/db:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - '7070:8080'
    depends_on:
      - db

  redis:
    image: redis:alpine
    ports:
      - '6060:6379'
    volumes:
      - ./redis:/data
